### Login utente

POST http://localhost:3000/api/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{  "email": "diaferiosamuele@gmail.com",  "password": "prova1234"}


### Registrazione utente

POST http://localhost:3000/api/auth/register HTTP/1.1
Accept: application/json
Content-Type: application/json

[1;39m{[0m
  [1;34m"email"[0m[1;39m:[0m [0;32m"diaferiosamuele@gmail.com"[0m[1;39m,[0m
  [1;34m"password"[0m[1;39m:[0m [0;32m"prova1234"[0m
[1;39m}[0m
{  "fullName": "Samuele Diaferio",  "email": "diaferiosamuele@gmail.com",  "password": "prova1234"}


### Logout

GET http://localhost:3000/api/auth/logout HTTP/1.1
Accept: application/json


### 
